### PR TITLE
Update Globus downloads to use Globus SDK (updated)

### PR DESCRIPTION
**Pull request by mauzey1**
Closes #1422 

This PR will only merge ed5da0f into `devel`.

### CODE REVIEW

**Comment by nathanlcarlson** [comment]
@sashakames  Here is the proper PR. Test when ever you get the chance.

**Comment by sashakames** [comment]
Thank you @mauzey1 @nathanlcarlson will test this on esgf-fedtest

**Comment by sashakames** [comment]
Dang got a 500 error on esgf-fedtest.  I didn't have the same issue with no selected datasets.  This was after I was redirected to Globus, logged into their portal and selected the destination on my personal.  Here's the error, unfortunately not so detailed: 
```[Wed Nov 27 17:08:22 2019] [error] [client ::1]   File "/usr/local/conda/envs/cog/lib/python2.7/site-packages/globus_sdk/base.py", line 553, in _request
[Wed Nov 27 17:08:22 2019] [error] [client ::1]     raise self.error_class(r)
[Wed Nov 27 17:08:22 2019] [error] [client ::1] TransferAPIError: (404, u'ClientError.NotFound', u"No such endpoint with legacy name 'llnlesgf'", u'sDgrR8U2u')``` 
somewhat surprising because I thought we used the UUIDs rather than legacy names for endpoints, although that one is correct.

**Comment by mauzey1** [comment]
@sashakames What was the dataset that you used for testing?

**Comment by mauzey1** [comment]
@sashakames 
I looked at the dataset that you used for testing Globus on CoG and it appears to have an incorrect endpoint name.  The id of the dataset is `cmip5.output1.MIROC.MIROC-ESM.lgm.fx.atmos.fx.r0i0p0.v20120828|aims3.llnl.gov`.  For some reason, it got published with the username of the endpoint, `llnlesgf`, but not the UUID of the endpoint.

**Comment by sashakames** [comment]
I tried a different dataset and the transfer was submitted without a problem!  Thanks for catching that @mauzey1

**Pull request merged**
