### PR TITLE
Update Globus downloads to use Globus SDK

### PR DESCRIPTION
**Pull request by mauzey1**
This change will replace the old Globus transfer API with Globlus SDK.  It also removes the X.509 endpoint activation section in the activateEndpoint fucntion that didn't appear to be in use in CoG.

### CODE REVIEW

**Comment by sashakames** [comment]
Thanks, Lets ensure testing is successful on this before merge into devel so no need to back out changes.

**Comment by nathanlcarlson** [comment]
This has successfully completed a transfer @sashakames . I am going to approve and merge it.

**Comment by sashakames** [comment]
Great!  @nathanlcarlson on what server were you able to test?  I thought on esgf-fedtest was registered (or did you register another client)?

**Comment by mauzey1** [comment]
@sashakames I tested the Globus transfer by running CoG on my RHEL 7 workstation.

**Comment by sashakames** [comment]
Thanks @mauzey1!  Nathan explained the peculiarities of testing from your desktop.  I'm inclined to attempt a test on esgf-fedtest prior to a merge and will try to do so Monday next week if not later today.

**Comment by sashakames** [comment]
On esgf-fedtest the selected datasets aren't picked up by the transfer view.  Will need to look into whats going on there.  Can't imagine that complicated a problem.

**Comment by mauzey1** [comment]
@sashakames @nathanlcarlson Are there Globus-enabled datasets on esgf-fedtest?  I don't see any on there.

**Comment by sashakames** [comment]
`https://esgf-fedtest.llnl.gov/search/esgf-llnl-dev/` -  search for `data_node aims3` or `esgf-data1`

**Comment by mauzey1** [comment]
I'm getting a 504 error with that link.

**Comment by sashakames** [comment]
Something isn't right with the server and I'll need to investigate but may not solve by COB today.

**Comment by sashakames** [comment]
Seems to be working when I opened a private firefox sesssion.  Might be some cookie issue.

**Comment by sashakames** [comment]
Apologies that was just the project view page.  The search page is timing out now and not sure why.

**Comment by nathanlcarlson** [comment]
Going to use #1423

**Pull request closed without merging**
