### PR TITLE
Oauth2 slcs

### PR DESCRIPTION
**Pull request by watucker**
Adds support for OAuth2 login via a customisable set of providers. Tested successfully in dev against https://slcs.ceda.ac.uk/.

Uses a copy of the `ESGFOAuth2` backend from [esgf-auth](https://github.com/ESGF/esgf-auth/blob/master/esgf_auth/backends/esgf.py).

### CODE REVIEW

**Comment by LucaCinquini** [comment]
Hi William, is this ready to be merged now? I thought you had some more work to do.
Thanks, L

**Comment by lukaszlacinski** [comment]
The code responsible for creating new CoG accounts has not been tested. Also if I remember correctly some code needs to be added to avoid account creation conflicts between OpenID and OAuth2.

**Comment by LucaCinquini** [comment]
Ok thanks . Maybe William will let me know if/when/what to merge.

**Comment by watucker** [comment]
Hi Luca. I threw this up as a PR just in-case we wanted to merge what we had before working on other issues. I've only tested the OAuth2 call-out (and my testing set-up is limited) so I can't speak for any other work that might need doing on the account-creation side of things.

**Comment by watucker** [comment]
Replaced by https://github.com/ESGF/COG/pull/4

**Pull request closed without merging**
